services:
  app:
    build: .
    container_name: ideasoft_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: ideasoft_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: ideasoft_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ideasoft_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: ideasoft_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  mysql_data: